spring.security.oauth2.client.registration.logto.client-name=logto
spring.security.oauth2.client.registration.logto.client-id=wqcii0ruf7b2q64izzujh
spring.security.oauth2.client.registration.logto.client-secret=l6DfdxQbr9Wkz8cLENUU6b1O9uS5NIKM
spring.security.oauth2.client.registration.logto.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.logto.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.logto.scope=openid,profile,email,offline_access
spring.security.oauth2.client.registration.logto.provider=logto

spring.security.oauth2.client.provider.logto.issuer-uri=http://localhost:3001/oidc
spring.security.oauth2.client.provider.logto.authorization-uri=http://localhost:3001/oidc/auth
spring.security.oauth2.client.provider.logto.jwk-set-uri=http://localhost:3001/oidc/jwks